### PR TITLE
Fixes Safari scrolling bug & beautifies main.css

### PR DESCRIPTION
**Pull request by Sam0711er**
This PR fixes the Safari scrolling bug (#15)

### CODE REVIEW

**Comment by b-g** [comment]
Hi @Sam0711er Many thanks for this! However this commit seems to be incomplete, as it just includes changes in `main.css` ... which is generated automatically from all the `style/*.scss` files. Please commit these as well, so that I can have a look. 🙏

**Comment by Sam0711er** [comment]
@b-g Here you go

**Comment by b-g** [comment]
Hi @Sam0711er, thanks for this! Yes scrolling works now in Safari ... but your changes killed the lazy loading of the images. Scrolling down in library (http://localhost:9966/library.html) yields just empty images ... close! :) Can you have a look once more?

**Comment by Sam0711er** [comment]
We might be able to discard these changes. Check #15.

**Comment by b-g** [comment]
@Sam0711er thanks for reaching out to Apple! Will close the PR as it seems unlikely that we need to do something on this end.

**Pull request closed without merging**
