### PR TITLE
Style improvements - fix #41

### LINKED ISSUE #41: Website looks mega horrible on mobile
Website looks mega horrible on mobile :( Part of the problem is that you even can't have it 100% on your mobile.

@jodunkel (or anyone else) any chance to gently improve this e.g. show the website as on desktop or at least style the landing site for mobile?

IMG_C341D7939476-1

### PR DESCRIPTION
**Pull request by felixhaeberle**
This is the first step to make the site work responsive.

- fixing security vulnerabilities
- cleanup style formatting
- remove unused styles
- remove unused home-header file
- rename right class to action-links
- beautify html files
- update comprehensible variable names
- introducing new breakpoints
- cleanup header css and introduce mixins
- update package.json to the latest stable versions
- add active-tab mixin
- add responsive design to front page
- add editorconfig file to fix same editor behavior
- insert final new line for the scss
- add new sass preprocessing
- preparing the header for responsive design
- add responsive header without search bar

For now, **only the front page works responsive**, but the other sites can be adapted faster now.

### CODE REVIEW

**Comment by b-g** [comment]
Hi @felixhaeberle! Wow! this is mega great! Many thanks for the effort! A few comment/feedback below:

1. Your changes break the navigation header for all subsites but the landing page e.g. 
[localhost:9966/library](http://localhost:9966/library/):

2019-09-23 at 16 57

2. The mobile version of the landing site looks much better! Yay! I still think a few small tiny details could be improved ... How fine grained to you want a review? (I would review it against https://www.figma.com/file/IPDkZy9bolQiXRGGnzIVHDDD/openmoji_website_v2)

3. The remaining subsites are still work in progress / "mega horrible" :) , right?

4. Please add yourself to the acknowledgements

Could you at least fix 1. before I merge it into master? Would you be willing to tackle the rest of the subsites as well? Happy to have Skype etc on this if helpful.

🙏!!

**Comment by felixhaeberle** [comment]
@b-g Cool! Thanks for your review. 👍

1. I'm going to fix those issues, sure, it can't be merged without.

2. I'm happy to receive feedback, please! Any feedback is welcome. I have also some in mind e.g. font sizes and spacings primarily. 🎨

3. Yeah, my bad! Will fix those the next days. I'm busy doing other open source and client work. But count me in for these changes. 👨🏻‍💻

4. Sure. Thanks! ✌️

I'm a bit concerned about the JS interacting and manipulating the layout/DOM. Some design decisions in Figma don't take into account this JS logic. I would rather step back from doing a pixel perfect redesign based on Figma, but iterating on the current design until we get to the favoured design results (of Figma?).

**Comment by b-g** [comment]
Great! Yes I agree the layout (as currently defined in Figma) is not on all ends ideal. May suggest the following approach: 

- you tackle first the subsite nav header bug ... we merge it
- then we have a quick call to get to know each other and to discuss possible directions for the new/update/responsive layout?
- if == ok for you, then ping me once you ready. I'm based in ET (CET - 6h) ... so a call in your afternoon/evening and my morning would be ideal. Looking forward to!

**Comment by felixhaeberle** [comment]
@b-g, found time to get into it and finish the missing piece! 👍

**Comment by b-g** [comment]
Hi @felixhaeberle! Great! 🙏! Before I merge it and deploy it, a tiny thing:

Could you remove border of the hamburger menu and increase the stroke width of the three lines to something like the black lines in the emojis below?
2019-10-03 at 11 54

Anything else looks good! Should we aim to have a quick Skype in the next days for how to proceed with 3.?

> 3. The remaining subsites are still work in progress / "mega horrible" :) , right?

**Comment by felixhaeberle** [comment]
Sure, will improve the hamburger menu. I used the icons out of our icon set and don't introduced new ones - so the svg would then be proportionally bigger without padding or margin and without border. Going to adjust the close menu to the same size too. 👍

About the call: Let me restore my skype and after I tell you my nickname and the preferred time/date. :)

**Comment by b-g** [comment]
👍🙏!

**Comment by felixhaeberle** [comment]
I fixed the icon! 🚢 

My skype handle is live:kontakt_16488 (? is that right, I don't know)
The "invite link" provided by skype to share my account is https://join.skype.com/invite/hrgbyDX7ivlY
You can also add and search me by my real name I think: Felix Häberle
I'm used to "zoom" and never used Skype in 5 years. 😅

How about the 8th of October at 11:00 your time (17:00 my time)? 🕚

**Comment by b-g** [comment]
@felixhaeberle Merged! (Will deploy it in the next days)

RE: Skype ... added you to my contacts. ✅ 🕚 Oct 8 11:30a your time (17:30 my time). Looking forward!

RE: Menu icon ... Great + thanks!

**Pull request merged**
