### PR TITLE
Adds App Store Download Badge & Fixes grammatical error on About page

### LINKED ISSUE #37: Add Link to App Store

### PR DESCRIPTION
**Pull request by Sam0711er**
Fixes #37

### CODE REVIEW

**Comment by Sam0711er** [comment]
image

**Comment by b-g** [comment]
@Sam0711er Thanks for this! But I would vote to leave the menu item as it is and instead add the "App Store" badge at the landing site: 

Try OpenMoji on your phone
"App Store Badge"

**Comment by Sam0711er** [comment]
@b-g Wasn’t ready for merge yet, @jodunkel still needs to work on css styling for the button

**Comment by b-g** [comment]
@Sam0711er Made a basic fix ... but could need some more love :)

**Pull request merged**
