### PR TITLE
Responsive layout

### LINKED ISSUE #47: Make subpages responsive (improve mobile)

### PR DESCRIPTION
**Pull request by felixhaeberle**
This is a first proposal on how to fix #47 - the responsive behavior of the website. I tried to minimize the amount of changed markup and focused on aligning the content in a useful way. 
In some places it already works well, other places need a bit improvement but I'm not sure.
This is not considered final! Please suggest your changes and give feedback :) 
Happy to do them! 🚀

### CODE REVIEW

**Comment by b-g** [comment]
@felixhaeberle Hope all is well! We changed some content ... please update from Master this PR. + Any news on it? :)

**Comment by felixhaeberle** [comment]
hey @b-g, sorry for being late! this will be ready at the end of the weekend :)

**Comment by felixhaeberle** [comment]
I'm finally done with rebasing this work to the current HEAD 😅 
Now I'm about to get the latest changes based on the feedback in. 🚀

**Comment by carlinmack** [comment]
can you check I didn't break anything with that merge? I think I only added the most recent commit

**Comment by b-g** [comment]
@felixhaeberle Many thanks for this! Just merged it to Master ... Yay!

**Pull request merged**
