### PR TITLE
add colorfont warn info

### PR DESCRIPTION
**Pull request by felixhaeberle**
fixing #49

### CODE REVIEW

**Comment by felixhaeberle** [comment]
updated #49 🚀

**Comment by b-g** [comment]
@felixhaeberle Thanks + merged!

But could you style the "discussion" link in the same grey and simply underline it?

Screen Shot 2019-12-04 at 09 17 49

No need for a PR ... just push to master. Thanks!

**Comment by felixhaeberle** [comment]
@b-g Ha! Already had that but then switched back for consistency 😄 
Sure! :)

**Comment by b-g** [comment]
@felixhaeberle Sorry! Please put it back in ...

**Pull request merged**
